### PR TITLE
Testing with Jest

### PR DESCRIPTION
**Pull request by NtwaliHeritier**
In this pull request, we used the Jest testing tool to test every function needed by the application to run. We divided the test cases into 4 categories  : 
- Test cases that test constructors.
- Test cases that test helper functions.
- Test cases that test project manipulation functions.
- Test cases that test task manipulation functions.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! Creating new modules specifically for testing is introducing some different logic for some of your functions and some functions have completely been left out. I see a possibility of importing your logic from the `render_todolist.js` module and testing it directly. I understand that your initial project structure is the cause of the testing challenges you're facing and I commend you for improvising. Please test the `render_todolist.js` module or consider directly refactoring it so that you can test it better.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by khalilhamdii** [comment]
> ### Changes Required! ♻️
> Hi team! Creating new modules specifically for testing is introducing some different logic for some of your functions and some functions have completely been left out. I see a possibility of importing your logic from the `render_todolist.js` module and testing it directly. I understand that your initial project structure is the cause of the testing challenges you're facing and I commend you for improvising. Please test the `render_todolist.js` module or consider directly refactoring it so that you can test it better.
> 
> **Kindly make the necessary changes and submit another code review request.**
> _Feel free to reach me on slack for any inquiries about this review._ 😉
> **Treasure Kabareebe**
> [Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

Thank you for your review! It was really helpful... We did refactor the render Todolist module into 4 modules to make it easy for testing and tested as requested 👍

**Comment by sumancrest0001** [comment]
### Status: Changes required :gear:
Thank you, @NtwaliHeritier and @khalilhamdii for implementing the changes suggested by the previous TSE. All the test suites are passing. 
**[Required]** But we need to improve the readme file. Even though you have an attractive readme file, details about the local setup and the running test are missing. Can you please update it? [Reference](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

[Required] PR should be descriptive and give us details about the changes you made or feature you implemented and any other important info. Please consider it in the next projects. [Reference](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**Please make the necessary change and submit for another review. If you have any queries regarding the review, please contact me on Slack. Suman Shrestha**

**Happy coding !!!**

**Review by rOluochKe — APPROVED** [review]
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
